LazyLoad=function(k){function l(c,b){var d=k.createElement(c),e;for(e in b)b.hasOwnProperty(e)&&d.setAttribute(e,b[e]);return d}function d(c){var b=q[c],d,e;b&&(d=b.callback,e=b.urls,e.shift(),m=0,e.length||(d&&d.call(b.context,b.obj),q[c]=null,r[c].length&&f(c)))}function h(){var c=navigator.userAgent;e={async:!0===k.createElement("script").async};(e.webkit=/AppleWebKit\//.test(c))||(e.ie=/MSIE/.test(c))||(e.opera=/Opera/.test(c))||(e.gecko=/Gecko\//.test(c))||(e.unknown=!0)}function f(c,b,f,m,s){var x=
function(){d(c)},u="css"===c,v=[],g,o,i,n;e||h();if(b)if(b="string"===typeof b?[b]:b.concat(),u||e.async||e.gecko||e.opera)r[c].push({urls:b,callback:f,obj:m,context:s});else{g=0;for(o=b.length;g<o;++g)r[c].push({urls:[b[g]],callback:g===o-1?f:null,obj:m,context:s})}if(!q[c]&&(n=q[c]=r[c].shift())){t||(t=k.head||k.getElementsByTagName("head")[0]);b=n.urls;g=0;for(o=b.length;g<o;++g)f=b[g],u?i=e.gecko?l("style"):l("link",{href:f,rel:"stylesheet"}):(i=l("script",{src:f}),i.async=!1),i.className="lazyload",
i.setAttribute("charset","utf-8"),e.ie&&!u?i.onreadystatechange=function(){if(/loaded|complete/.test(i.readyState)){i.onreadystatechange=null;x()}}:u&&(e.gecko||e.webkit)?e.webkit?(n.urls[g]=i.href,p()):(i.innerHTML='@import "'+f+'";',j(i)):i.onload=i.onerror=x,v.push(i);g=0;for(o=v.length;g<o;++g)t.appendChild(v[g])}}function j(c){var b;try{b=!!c.sheet.cssRules}catch(e){m+=1;200>m?setTimeout(function(){j(c)},50):b&&d("css");return}d("css")}function p(){var c=q.css,b;if(c){for(b=s.length;0<=--b;)if(s[b].href===
c.urls[0]){d("css");break}m+=1;c&&(200>m?setTimeout(p,50):d("css"))}}var e,t,q={},m=0,r={css:[],js:[]},s=k.styleSheets;return{css:function(c,b,d,e){f("css",c,b,d,e)},js:function(c,b,d,e){f("js",c,b,d,e)}}}(this.document);LoadLib=function(){function k(d){for(var h=0,f=!1,h=0;h<l.length;h++)l[h]==d&&(f=!0);if(f)return!0;l.push(d);return!1}var l=[];return{css:function(d,h,f,j){k(d)||LazyLoad.css(d,h,f,j)},js:function(d,h,f,j){k(d)||LazyLoad.js(d,h,f,j)}}}(this.document);var WebFontConfig;
if("undefined"==typeof embed_path||"undefined"==typeof embed_path)var embed_path=getEmbedScriptPath("storyjs-embed.js").split("js/")[0];function getEmbedScriptPath(k){for(var l=document.getElementsByTagName("script"),d="",h="",f=0;f<l.length;f++)l[f].src.match(k)&&(d=l[f].src);""!=d&&(h="/");return d.split("?")[0].split("/").slice(0,-1).join("/")+h}
(function(){"object"==typeof url_config?createStoryJS(url_config):"object"==typeof timeline_config?createStoryJS(timeline_config):"object"==typeof storyjs_config?createStoryJS(storyjs_config):"object"==typeof config&&createStoryJS(config)})();
function createStoryJS(k,l){var d,h,f,j,p,e,t,q,m,r,s,c,b,w;function B(){LoadLib.js(a.js,E)}function E(){m=!0;"en"!=a.lang?LazyLoad.js(e,x):r=!0;g()}function x(){r=!0;g()}function u(){d=!0;g()}function v(){h=!0;g()}function g(){40<s||(s++,m&&c&&d&&h&&r?b||(b=!0,VMM.debug=a.debug,o=new VMM.Timeline(a.id),o.init(a),z.resolve(o),C&&VMM.bindEvent(global,onHeadline,"HEADLINE")):setTimeout("onloaded_check_again();",250))}var o,i,n,y,C=!1,D="";s=0;h=d=r=w=c=m=b=!1;t=embed_path+"css/";q=embed_path+"js/";
e=embed_path+"js/locale/";f=!1;j=embed_path+"css/themes/font/";p=void 0;var a={version:"2.24",debug:!1,type:"timeline",id:"storyjs",embed_id:"timeline-embed",embed:!0,width:"100%",height:"100%",source:"https://docs.google.com/spreadsheet/pub?key=0Agl_Dv6iEbDadFYzRjJPUGktY0NkWXFUWkVIZDNGRHc&output=html",lang:"en",font:"default",css:t+"timeline.css?2.24",js:"",api_keys:{google:"",flickr:"",twitter:""},gmap_key:""},A=[{name:"Merriweather-NewsCycle",google:["News+Cycle:400,700:latin","Merriweather:400,700,900:latin"]},
{name:"NewsCycle-Merriweather",google:["News+Cycle:400,700:latin","Merriweather:300,400,700:latin"]},{name:"PoiretOne-Molengo",google:["Poiret+One::latin","Molengo::latin"]},{name:"Arvo-PTSans",google:["Arvo:400,700,400italic:latin","PT+Sans:400,700,400italic:latin"]},{name:"PTSerif-PTSans",google:["PT+Sans:400,700,400italic:latin","PT+Serif:400,700,400italic:latin"]},{name:"PT",google:["PT+Sans+Narrow:400,700:latin","PT+Sans:400,700,400italic:latin","PT+Serif:400,700,400italic:latin"]},{name:"DroidSerif-DroidSans",
google:["Droid+Sans:400,700:latin","Droid+Serif:400,700,400italic:latin"]},{name:"Lekton-Molengo",google:["Lekton:400,700,400italic:latin","Molengo::latin"]},{name:"NixieOne-Ledger",google:["Nixie+One::latin","Ledger::latin"]},{name:"AbrilFatface-Average",google:["Average::latin","Abril+Fatface::latin"]},{name:"PlayfairDisplay-Muli",google:["Playfair+Display:400,400italic:latin","Muli:300,400,300italic,400italic:latin"]},{name:"Rancho-Gudea",google:["Rancho::latin","Gudea:400,700,400italic:latin"]},
{name:"Bevan-PotanoSans",google:["Bevan::latin","Pontano+Sans::latin"]},{name:"BreeSerif-OpenSans",google:["Bree+Serif::latin","Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800:latin"]},{name:"SansitaOne-Kameron",google:["Sansita+One::latin","Kameron:400,700:latin"]},{name:"Lora-Istok",google:["Lora:400,700,400italic,700italic:latin","Istok+Web:400,700,400italic,700italic:latin"]},{name:"Pacifico-Arimo",google:["Pacifico::latin","Arimo:400,700,400italic,700italic:latin"]}],
z;if("object"==typeof k)for(y in k)Object.prototype.hasOwnProperty.call(k,y)&&(a[y]=k[y]);"undefined"!=typeof l&&(a.source=l);"object"==typeof url_config&&(C=!0,!a.source.match("docs.google.com")&&(!a.source.match("json")&&!a.source.match("storify"))&&(a.source="https://docs.google.com/spreadsheet/pub?key="+a.source+"&output=html"));a.js.match("locale")&&(a.lang=a.js.split("locale/")[1].replace(".js",""),a.js=q+"timeline-min.js?2.24");a.js.match("/")||(a.css=t+a.type+".css?2.24",a.js=q+a.type,a.js=
a.debug?a.js+".js?2.24":a.js+"-min.js?2.24",a.id="storyjs-"+a.type);e=a.lang.match("/")?a.lang:e+a.lang+".js?2.24";(function(){var b="storyjs-embed";i=document.createElement("div");n=a.embed_id!=""?document.getElementById(a.embed_id):document.getElementById("timeline-embed");n.appendChild(i);i.setAttribute("id",a.id);if(a.width.toString().match("%"))n.style.width=a.width.split("%")[0]+"%";else{a.width=a.width-2;n.style.width=a.width+"px"}if(a.height.toString().match("%")){n.style.height=a.height;
b=b+" full-embed";n.style.height=a.height.split("%")[0]+"%"}else{b=a.width.toString().match("%")?b+" full-embed":b+" sized-embed";a.height=a.height-16;n.style.height=a.height+"px"}n.setAttribute("class",b);n.setAttribute("className",b);i.style.position="relative"})();LoadLib.css(a.css,function(){c=true;g()});if("default"==a.font)d=h=!0;else{a.font.match("/")?(p=a.font.split(".css")[0].split("/"),p=p[p.length-1],j=a.font):(p=a.font,j=j+a.font+".css?2.24");LoadLib.css(j,u);for(j=0;j<A.length;j++)p==
A[j].name&&(f=!0,WebFontConfig={google:{families:A[j].google}});f?LoadLib.js("http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js",v):h=!0}try{D=parseFloat(jQuery.fn.jquery),w=D<parseFloat("1.7.1")?!1:!0}catch(F){w=!1}w?(z=new jQuery.Deferred,B()):LoadLib.js("http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js",B);this.onloaded_check_again=function(){g()};return z};
